/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main(String[] args) {
        LinkedList ll=new LinkedList();
        ll.insert(1);
        ll.insert(2);
        ll.insert(3);
        ll.insert(4);
        System.out.println(ll.getValue(ll));
        System.out.println(ll.toString(ll));

    }
}
