/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.max;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void maximum(){
        BinarySearch binarySearch=new BinarySearch();
        binarySearch.add(40);
        binarySearch.add(20);
        binarySearch.add(50);
        String result="maximum value is: 50";
        assertEquals("test for max function ",result,String.valueOf(binarySearch.maximam()));
    }
}
