/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.max;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void maximum(){

        BinaryTree binaryTree=new BinaryTree();
        Node root=new Node(2);
        root.left=new Node(7);
        root.right=new Node(5);
        root.left.left=new Node(2);
        root.left.right=new Node(6);
        root.right.left=new Node(50);
        root.right.right=new Node(8);
        String result="maximum value is: 50";
        assertEquals("test for max function ",result,String.valueOf(binaryTree.maximam(root)));
    }
}
