/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.zip;

import com.google.common.collect.LinkedListMultimap;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }
    public static void zipFunction(LinkedList first,LinkedList sec){
        LinkedList ll3=new LinkedList();
        ll3=ll3.zip(first,sec);
        System.out.println("list 1: "+first.getValue(first));
        System.out.println("lisr 2: "+sec.getValue(sec));
        System.out.println(ll3.getValue(ll3));

    }

    public static void main(String[] args) {

        LinkedList ll1=new LinkedList();
        ll1.add(1);
        ll1.add(3);
        ll1.add(5);
        ll1.add(7);
        System.out.println(ll1.tail);
        LinkedList ll2=new LinkedList();
        ll2.add(2);
        ll2.add(4);
        ll2.add(6);
        ll2.add(8);


        zipFunction(ll1,ll2);

    }



}
