/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.insertions;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void insertions(){
        LinkedList ll=new LinkedList();
        ll.add(1);
        ll.add(2);
        ll.add(3);
        ll.add(4);
        ll.add(5);
        ll.add(6);
        ll.Append(ll,10);
        String result1="[1, 2, 3, 4, 5, 6, 10]";
        assertEquals("this test for Append",result1,String.valueOf(ll.getValue(ll)));
        ll.insertBefore(ll,4,12);
        String result2="[1, 2, 3, 12, 4, 5, 6, 10]";
        assertEquals("this test for insert before",result2,String.valueOf(ll.getValue(ll)));
        ll.insertAfter(ll,4,16);
        String result3="[1, 2, 3, 12, 4, 16, 5, 6, 10]";
        assertEquals("this test for insert after",result3,String.valueOf(ll.getValue(ll)));
        ll.insertBefore(ll,1,12);
        String result4="[12, 1, 2, 3, 12, 4, 16, 5, 6, 10]";
        assertEquals("this test for insert before first element",result4,String.valueOf(ll.getValue(ll)));
        ll.insertAfter(ll,10,16);
        String result5="[12, 1, 2, 3, 12, 4, 16, 5, 6, 10, 16]";
        assertEquals("this test for insert after last element",result5,String.valueOf(ll.getValue(ll)));

        LinkedList ll2=new LinkedList();
        ll2.Append(ll2,10);
        String result6="[]";
        assertEquals("this test for Append empty array",result6,String.valueOf(ll2.getValue(ll2)));
        ll2.insertBefore(ll2,4,12);
        String result7="[]";
        assertEquals("this test for insert before empty array",result7,String.valueOf(ll2.getValue(ll2)));
        ll2.insertAfter(ll2,4,16);
        String result8="[]";
        assertEquals("this test for insert after empty array",result8,String.valueOf(ll2.getValue(ll2)));
    }
}
