/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main(String[] args) {
        Queue<Integer>queue=new Queue<>();
        queue.pseudoEnqueue(1);
        queue.pseudoEnqueue(2);
        queue.pseudoEnqueue(3);
        queue.pseudoEnqueue(4);
        queue.pseudoEnqueue(5);
//        System.out.println(queue.pesudoDequeue());

        System.out.println(queue.getValue());
        System.out.println(queue.pesudoDequeue());
        System.out.println(queue.getValue());
    }
}
