/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void pseudoQueue(){
        Queue<Integer>queue=new Queue<>();

        queue.pesudoDequeue();
        String result0="null";
        assertEquals("this for pseudo dequeue with empty queue",result0,String.valueOf(queue.pesudoDequeue()));
        queue.pseudoEnqueue(1);
        queue.pseudoEnqueue(2);
        queue.pseudoEnqueue(3);
        queue.pseudoEnqueue(4);
        queue.pseudoEnqueue(5);
        String result2="5-> 4-> 3-> 2-> 1-> null";
        assertEquals("this for pseudo enqueue with queue",result2,queue.getValue());
        Integer result3=1;
        assertEquals("this for pseudo dequeue with queue",result3,queue.pesudoDequeue());
    }
}
