/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void pseudoQueue(){
        Queue<Integer>queue=new Queue<>();
        queue.pesudoDequeue();
        String result0="null";
        assertEquals("this for pseudo dequeue with empty queue",result0,String.valueOf(queue.pesudoDequeue()));
        queue.pseudoEnqueue(5);
        Integer result1=5;
        assertEquals("this for pseudo enqueue with empty queue",result1,queue.front.value);
        queue.enqueue(1);
        queue.enqueue(2);
        queue.enqueue(3);
        queue.enqueue(4);
        queue.pseudoEnqueue(10);
        Integer result2=10;
        assertEquals("this for pseudo enqueue with queue",result2,queue.front.value);
        queue.pesudoDequeue();
        Integer result3=3;
        assertEquals("this for pseudo dequeue with queue",result3,queue.rear.value);
    }
}
