/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testForHashTable(){
        HashTable hashTable=new HashTable();
        hashTable.add("ahmad",3);
        hashTable.add("ahmads",31);
        hashTable.add("noor",21);
        hashTable.add("mom",7);
        hashTable.add("noor",7);
        String result0="[null, {noor: 7} -> null, {ahmad: 3} -> null, null, {ahmads: 31} -> {mom: 7} -> null]";
        assertEquals("this for all hashTable",result0,hashTable.print());

        String result1="noor: 7";
        assertEquals("this for get",result1,hashTable.get("noor"));

        String result2="is not exist";
        assertEquals("this for get",result2,hashTable.get("noorssas"));

        String result3="index: 1";
        assertEquals("this for hash",result3,hashTable.hash("noor"));

        String result4="is not exist";
        assertEquals("this for hash",result4,hashTable.hash("noorvvvvv"));

        assertTrue("this for is contain",hashTable.isContain("mom"));

        assertFalse("this for is contain",hashTable.isContain("xxxx"));
    }
}
