/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test public void testOfSortArray(){
        int[]arr={20,18,12,8,5,-2};
        MergeSort mergeSort=new MergeSort();
        mergeSort.sort(arr);
        String result0="[-2, 5, 8, 12, 18, 20]";
        assertEquals(result0, Arrays.toString(arr));

        int[]arr1={5,12,7,5,5,7};
        MergeSort mergeSort1=new MergeSort();
        mergeSort1.sort(arr1);
        String result1="[5, 5, 5, 7, 7, 12]";
        assertEquals(result1,Arrays.toString(arr1));

        int[]arr2={2,3,5,7,13,11};
        MergeSort mergeSort2=new MergeSort();
        mergeSort2.sort(arr2);
        String result2="[2, 3, 5, 7, 11, 13]";
        assertEquals(result2,Arrays.toString(arr2));
    }
}
