/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.zip;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void zipList1(){
        LinkedList ll1=new LinkedList();
        ll1.add(1);
        ll1.add(3);
        ll1.add(5);
        ll1.add(7);
        LinkedList ll2=new LinkedList();
        ll2.add(2);
        ll2.add(4);
        ll2.add(6);
        ll2.add(8);
        LinkedList ll3=new LinkedList();
        ll3=ll3.zip(ll1,ll2);
        String result="[1, 2, 3, 4, 5, 6, 7, 8]";
        assertEquals("this for zip list: ",result,String.valueOf(ll3.getValue(ll3)));
    }
    @Test public void zipList2(){
        LinkedList ll1=new LinkedList();
        ll1.add(1);
        ll1.add(3);
        ll1.add(5);
        ll1.add(7);
        ll1.add(9);
        LinkedList ll2=new LinkedList();
        ll2.add(2);
        ll2.add(4);
        ll2.add(6);
        ll2.add(8);
        LinkedList ll3=new LinkedList();
        ll3=ll3.zip(ll1,ll2);
        String result="[1, 2, 3, 4, 5, 6, 7, 8, 9]";
        assertEquals("this for zip list: ",result,String.valueOf(ll3.getValue(ll3)));
    }
    @Test public void zipList3(){
        LinkedList ll1=new LinkedList();
        ll1.add(1);
        ll1.add(3);
        ll1.add(5);
        ll1.add(7);
        LinkedList ll2=new LinkedList();
        ll2.add(2);
        ll2.add(4);
        ll2.add(6);
        ll2.add(8);
        ll2.add(11);
        LinkedList ll3=new LinkedList();
        ll3=ll3.zip(ll1,ll2);
        String result="[1, 2, 3, 4, 5, 6, 7, 8, 11]";
        assertEquals("this for zip list: ",result,String.valueOf(ll3.getValue(ll3)));
    }
}
