/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.animal.shelter;

import org.junit.Test;

import java.util.Objects;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void animalShelter(){
        Animal cat1=new Cat("cat",2);
        Animal dog1=new Dog("dog",1);
        Animal cat2=new Cat("cat",4);
        Animal dog2=new Dog("dog",3);
        Animal cow=new Animal("cow",9);

        AnimalShelter<Objects>animalShelter=new AnimalShelter<>();
        animalShelter.enqueue(cat1);
        animalShelter.enqueue(dog1);
        animalShelter.enqueue(cat2);
        animalShelter.enqueue(dog2);
        animalShelter.enqueue(cow);

        String result0="Animal{type='cat', age=2}";
        assertEquals("this for pref cat",result0,String.valueOf(animalShelter.dequeue("cat")));
        String result1="Animal{type='dog', age=1}";
        assertEquals("this for pref dog",result1,String.valueOf(animalShelter.dequeue("dog")));
        assertNull("this for pref other animal",animalShelter.dequeue("cow"));

    }
}
