/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.*;


public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main(String[] args) {
        Graph<String,Integer>graph1=new Graph<>();
        graph1.undirectedEdge("pan","are",150);
        graph1.undirectedEdge("pan","met",82);
        graph1.undirectedEdge("are","met",99);
        graph1.undirectedEdge("are","mons",42);
        graph1.undirectedEdge("met","narn",37);
        graph1.undirectedEdge("met","nabo",26);
        graph1.undirectedEdge("met","mons",105);
        graph1.undirectedEdge("mons","nabo",73);
        graph1.undirectedEdge("narn","nabo",250);
        System.out.println(graph1);
        System.out.println(graph1.isConnected(new String[]{"met", "pan"}));
        System.out.println(graph1.isConnected(new String[]{"are", "mons","nabo"}));
        System.out.println(graph1.isConnected(new String[]{"nabo", "pan"}));
        System.out.println(graph1.isConnected(new String[]{"narn", "are","nabo"}));

    }


}
