/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.left.join;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void hashLeft(){
        HashTable hashTable1=new HashTable();
        hashTable1.add("Ahmad","good");
        hashTable1.add("Noor","bad");
        hashTable1.add("Ali","noob");
        hashTable1.add("Mohammad","excellent");
        hashTable1.get("Noor");
        HashTable hashTable2=new HashTable();
        hashTable2.add("Ahmad","css");
        hashTable2.add("Noor","java");
        hashTable2.add("Ali","javaScript");
        hashTable2.add("Lila","excellent");
        String result="[[Ahmad, good, css], [Ali, noob, javaScript], [Mohammad, excellent, NULL], [Noor, bad, java]]";
        assertEquals("for hash left",result, String.valueOf(Library.leftJoin(hashTable1,hashTable2)));
    }
}
