/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void binarySearch(){

        BinarySearch binarySearch=new BinarySearch();
        binarySearch.add(40);
        binarySearch.add(20);
        binarySearch.add(50);
        binarySearch.add(100);

        String result0="[40, 20, 50, 100]";
        assertEquals("this test for preorder",result0,String.valueOf(binarySearch.preOrder()));
        String result1="[20, 40, 50, 100]";
        assertEquals("this test for inorder",result1,String.valueOf(binarySearch.inOrder()));
        String result2="[20, 50, 100, 40]";
        assertEquals("this test for post-order",result2,String.valueOf(binarySearch.postOrder()));
        assertTrue("this for correct contain",binarySearch.contains(20));
        assertFalse("this for false contain",binarySearch.contains(30));
    }
}
