/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void linkedList(){
        LinkedList ll=new LinkedList();
        ll.insert(1);
        ll.insert(2);
        ll.insert(3);
        ll.insert(4);
        String result1="[1, 2, 3, 4]";
        assertEquals("this test for insert value",result1,String.valueOf(ll.getValue(ll)));
        String result2="{1} -> {2} -> {3} -> {4} ->  NULL";
        assertEquals("this test for toString fun",result2,ll.toString(ll));

    }
}
