/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.fizz.buzz;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void FizzBuzz(){
        KeyTree<Integer> keyTree0=new KeyTree<>();
        Node root0=new Node(3);
        String result0="[Fizz]";
        assertEquals("this for divisible by 3 ",result0,String.valueOf(keyTree0.breadth(root0)));
        KeyTree<Integer> keyTree1=new KeyTree<>();
        Node root1=new Node(5);
        String result1="[Buzz]";
        assertEquals("this for divisible by 5 ",result1,String.valueOf(keyTree1.breadth(root1)));
        KeyTree<Integer> keyTree=new KeyTree<>();
        Node root=new Node(3);
        root.left=new Node(5);
        root.mid=new Node(10);
        root.right=new Node(30);
        root.left.left=new Node(20);
        root.left.right=new Node(6);
        root.mid.mid=new Node(15);
        root.right.left=new Node(9);
        root.right.right=new Node(8);
        String result="[Fizz, Buzz, Buzz, FizzBuzz, Buzz, Fizz, FizzBuzz, Fizz, 8]";
        assertEquals("this for all case ",result,String.valueOf(keyTree.breadth(root)));
    }
}
