/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main(String[] args) {
//        Stack<Integer>stack=new Stack<>();
//        stack.pop();
//        stack.peek();
//        System.out.println(stack.getValue());
//        stack.push(1);
//        stack.push(2);
//        stack.push(3);
//        stack.push(4);
//        System.out.println(stack.getValue());
//        System.out.println(stack.peek());
//        System.out.println(stack.pop());
//        System.out.println(stack.getValue());

        Queue<Integer>queue=new Queue<>();
        System.out.println(queue.dequeue());
        queue.enqueue(1);
        queue.enqueue(2);
        queue.enqueue(3);
        queue.enqueue(4);
        System.out.println(queue.getValue());
        System.out.println(queue.dequeue());
        System.out.println(queue.getValue());
    }
}
