/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.brackets;

import java.util.Arrays;
import java.util.HashMap;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }
    public static boolean balanceBracket(String string){
        Stack<Character>stack=new Stack<>();
        for (int i=0;i<string.length();i++){
            if (string.charAt(i)=='{'||string.charAt(i)=='['||string.charAt(i)=='('){
                stack.push(string.charAt(i));
            }else {
                if (stack.isEmpty()){
                    return false;
                }else {
                    if (string.charAt(i)=='}'&&stack.pop()!='{'){
                        return false;
                    }
                    if (string.charAt(i)==']'&&stack.pop()!='['){
                        return false;
                    }
                    if (string.charAt(i)==')'&&stack.pop()!='('){
                        return false;
                    }
                }
            }
        }
        return stack.isEmpty();
    }
    public static void main(String[] args) {
        System.out.println(balanceBracket("{[fdddffd(4544)]}"));
        System.out.println(balanceBracket("{(})"));
    }
}
