/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort.array;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }
    public static String sortedArray(int[] arr){
//        int[]arr={2,4,1,6,6,6,-5,6,8};
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                int temp= 0;
                if (arr[i] > arr[j]) {
                    temp= arr[i];
                    arr[i] = arr[j];
                    arr[j] = temp;
                }
            }

            System.out.println(arr[i]);
        }
        return Arrays.toString(arr);
    }

    public static void main(String[] args) {
        System.out.println(sortedArray(new int[]{2, 4, 1, 6, 6, 6, -5, 6, 8}));
    }
}
