/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void graphTest(){
        Graph<String,Integer>graph=new Graph<>();
        graph.undirectedEdge("a","b",150);
        graph.undirectedEdge("a","c",140);
        graph.undirectedEdge("d","c",60);
        graph.undirectedEdge("f","a",70);
        String result1="true $150";
        assertEquals(result1,graph.isConnected(new String[]{"a", "b"}));
        String result2="true $200";
        assertEquals(result2,graph.isConnected(new String[]{"a", "c","d"}));
        String result3="false $0";
        assertEquals(result3,graph.isConnected(new String[]{"a", "c","f"}));
        String result4="false $0";
        assertEquals(result4,graph.isConnected(new String[]{"a"}));
        String result5="false $0";
        assertEquals(result5,graph.isConnected(new String[]{}));

    }
}
