/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort.array;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testOfSortArray(){
        String result0="[-2, 5, 8, 12, 18, 20]";
        assertEquals(result0,Library.sortedArray(new int[]{20,18,12,8,5,-2}));
        String result1="[5, 5, 5, 7, 7, 12]";
        assertEquals(result1,Library.sortedArray(new int[]{5,12,7,5,5,7}));
        String result2="[2, 3, 5, 7, 11, 13]";
        assertEquals(result2,Library.sortedArray(new int[]{2,3,5,7,13,11}));
    }
}
