/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main(String[] args) {
        int[]arr={8,4,23,42,16,15};
        MergeSort mergeSort=new MergeSort();
        mergeSort.sort(arr);
        System.out.println(Arrays.toString(arr));
    }
}
