/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import java.util.Arrays;
import java.util.HashMap;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static String repeated(String name){
        String[] word =name.split("(?<=[,.' '])|(?=[,.' '])|\\s+");/*this line copy from https://stackoverflow.com/questions/13615939/java-split-string-into-words-commas-and-full-stops*/
        HashMap<String,Integer>hashMap=new HashMap<>();
        for (int i = 0; i < word.length; i++) {
            if (!word[i].equals(" ")&&!word[i].equals(",")&&!word[i].equals(".")){
                if (hashMap.containsKey(word[i].toLowerCase())){
                    return "is Repeated: "+word[i];
                }else {
                    hashMap.put(word[i].toLowerCase(),0);

                }
            }

        }
        return "didn't have repeated";
    }
    public static void main(String[] args) {

        String name="It was the best  of  times, it was the worst of times...";
//        System.out.println(Arrays.toString(word));
        System.out.println(repeated(name));
    }
}
