/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void repeated(){
        String name0="Once upon a time, there was a brave princess who...";
        String result0="is Repeated: a";
        assertEquals(result0,Library.repeated(name0));

        String name1="It was the best of times, it was the worst of times...";
        String result1="is Repeated: it";
        assertEquals(result1,Library.repeated(name1));

        String name2="It was a queer, sultry summer, the summer they electrocuted";
        String result2="is Repeated: summer";
        assertEquals(result2,Library.repeated(name2));
    }
}
