/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick.sort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testOfSortArray(){
        int[]arr0={20,18,12,8,5,-2};
        String result0="[-2, 5, 8, 12, 18, 20]";
        assertEquals(result0, Arrays.toString(Library.quickSort(arr0,0,arr0.length-1)));
        String result1="[5, 5, 5, 7, 7, 12]";
        int[]arr1={5,12,7,5,5,7};
        assertEquals(result1,Arrays.toString(Library.quickSort(arr1,0,arr1.length-1)));
        int[]arr2={2,3,5,7,13,11};
        String result2="[2, 3, 5, 7, 11, 13]";
        assertEquals(result2,Arrays.toString(Library.quickSort(arr2,0,arr2.length-1)));
    }
}
