/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void stack(){
        Stack<Integer>stack=new Stack<>();
//        stack.pop();
        assertTrue("check isEmpty",stack.isEmpty());
        assertNull("test for remove from empty",stack.pop());
        assertNull("test for vlaue of top from empty",stack.peek());
//        stack.peek();
        stack.push(1);
        stack.push(2);
        stack.push(3);
        stack.push(4);
        String result0="4-> 3-> 2-> 1-> null";
        assertEquals("test for value of stack",result0,stack.getValue());
        String result1="4";
        assertEquals("test for value of top",result1,String.valueOf(stack.peek()));
        stack.pop();
        String result2="3-> 2-> 1-> null";
        assertEquals("test for value of stack after remove",result2,stack.getValue());
    }
    @Test public void queue(){
        Queue<Integer>queue=new Queue<>();
        assertNull("test for remove from empty",queue.dequeue());
        queue.enqueue(1);
        queue.enqueue(2);
        queue.enqueue(3);
        queue.enqueue(4);
        String result0="1-> 2-> 3-> 4-> null";
        assertEquals("test for value of queue",result0,queue.getValue());
        queue.dequeue();
        String result1="2-> 3-> 4-> null";
        assertEquals("test for value of queue",result1,queue.getValue());
    }
}
