/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.breadth.first;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main(String[] args) {
        BinaryTree binaryTree=new BinaryTree();
        Node root=new Node(2);
        root.left=new Node(7);
        root.right=new Node(5);
        root.left.left=new Node(2);
        root.left.right=new Node(6);
        root.right.left=new Node(9);
        root.right.right=new Node(8);
        System.out.println(binaryTree.breadth(root));

    }
}
