/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void graphTest(){
        Graph<String>graph=new Graph<>();
        graph.undirectedEdge("a","b");
        graph.undirectedEdge("a","c");
        graph.undirectedEdge("d","c");
        graph.undirectedEdge("f","a");
        graph.addNode("m");
        String result="a==>[b, c, f]\n" +
                "b==>[a]\n" +
                "c==>[a, d]\n" +
                "d==>[c]\n" +
                "f==>[a]\n" +
                "m==>[]\n";
        assertEquals("this for graph",result,graph.toString());
        String result1="[b, c, f]";
        assertEquals("this for getNighbors",result1,String.valueOf(graph.getNighbors("a")));
        String result2="is'n exisit";
        assertEquals("this for getNighbors",result2,graph.getNighbors("n"));
        String result3="[a, b, c, d, f, m]";
        assertEquals("this for allNode",result3,String.valueOf(graph.allNode()));
        int result4=6;
        assertEquals("this for size",result4,graph.size());
        String result5="it's already exist";
        assertEquals("this for addNode",result5,graph.addNode("a"));

    }
}
