/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.fizz.buzz;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main(String[] args) {
        KeyTree<Integer> keyTree=new KeyTree<>();
        Node root=new Node(3);
        root.left=new Node(5);
        root.mid=new Node(10);
        root.right=new Node(30);
        root.left.left=new Node(20);
        root.left.right=new Node(6);
        root.mid.mid=new Node(15);
        root.right.left=new Node(9);
        root.right.right=new Node(8);
        System.out.println(keyTree.breadth(root));
    }
}
