/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void graphTest(){
        Graph<String>graph=new Graph<>();

        graph.undirectedEdge("a","b");
        graph.undirectedEdge("a","c");
        graph.undirectedEdge("d","c");
        graph.undirectedEdge("f","a");

        String result="[a, b, c, f, d]";
        assertEquals("this for brithdth first",result,graph.BreadthFirst("a").toString());

    }
}
